"""
report_generator.py
--------------------
Assembles the AI's output and the heuristic data into the final markdown
report, matching the 5-section format from the project spec.
"""

from datetime import datetime, timezone


def build_markdown(
    repo_info: dict,
    tech_stack: list,
    ai_result: dict,
    interview_questions: list | None = None,
) -> str:
    lines = []
    lines.append(f"# Repo Explainer: {repo_info['full_name']}")
    lines.append("")
    lines.append(f"> {repo_info['url']}  ")
    lines.append(f"> Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    lines.append("## 1. Summary")
    lines.append("")
    lines.append(ai_result.get("summary", "(no summary generated)"))
    lines.append("")

    lines.append("## 2. Tech Stack Detected")
    lines.append("")
    if tech_stack:
        for item in tech_stack:
            lines.append(f"- {item}")
    else:
        lines.append("- Could not confidently detect a tech stack from file names alone.")
    lines.append("")

    lines.append("## 3. Folder-by-Folder Explanation")
    lines.append("")
    folder_explanations = ai_result.get("folder_explanations", {})
    if folder_explanations:
        for folder, explanation in folder_explanations.items():
            label = "/ (root)" if folder == "." else f"`{folder}/`"
            lines.append(f"- **{label}** -- {explanation}")
    else:
        lines.append("- (no folder breakdown generated)")
    lines.append("")

    lines.append("## 4. Three Most Important Files to Read First")
    lines.append("")
    top_files = ai_result.get("top_files", [])
    if top_files:
        for i, entry in enumerate(top_files[:3], start=1):
            lines.append(f"{i}. **`{entry.get('path', '?')}`** -- {entry.get('why', '')}")
    else:
        lines.append("(none identified)")
    lines.append("")

    lines.append("## 5. Suggested Improvement")
    lines.append("")
    lines.append(ai_result.get("improvement", "(no suggestion generated)"))
    lines.append("")

    if interview_questions:
        lines.append("## Bonus: Interview Questions About This Codebase")
        lines.append("")
        for i, question in enumerate(interview_questions, start=1):
            lines.append(f"{i}. {question}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [RepoLens](https://github.com/) -- a GitHub Repo Explainer CLI.*")

    return "\n".join(lines)
